### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by AngeloMetal** [3rdIteration/btcrecover#126]
Hi, I get the following error once I run ``C:\Python39\python.exe seedrecover.py --help``:

```Traceback (most recent call last):
  File "C:\Users\bymet\Pictures\btcrecover2\seedrecover.py", line 30, in <module>
    from btcrecover import btcrseed
  File "C:\Users\bymet\Pictures\btcrecover2\btcrecover\__init__.py", line 2, in <module>
    from .btcrpass import *
  File "C:\Users\bymet\Pictures\btcrecover2\btcrecover\btcrpass.py", line 40, in <module>
    from lib.emip3 import emip3
  File "C:\Users\bymet\Pictures\btcrecover2\lib\emip3\emip3.py", line 5, in <module>
    from Crypto.Cipher import ChaCha20_Poly1305
ModuleNotFoundError: No module named 'Crypto' 
```
I've installed pycryptodome~=3.9.9 and all the other requirements. Have you any ideas what's the fault? Thank you.

**Comment by 3rdIteration** [comment]
Did you do the full install -r requirements.txt ?

**Comment by AngeloMetal** [comment]
Thanks, I installed them again and it worked. Issue is now closed.
