### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by keith01234** [3rdIteration/btcrecover#129]
Hi,

I have used BTCrecover previously and has worked exceptionally well for me, however this time around when I installed it on a new ubuntu machine I am getting the following error while executing any commands:

python3 btcrecover.py --no-dupchecks --passwordlist passlist.txt --addr-limit 10 --bip32-path "m/44'/60'/0'/0" --wallet-type ethereum

Starting btcrecover 1.7.1-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 38, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrpass.py", line 4108, in parse_arguments
    loaded_wallet = WalletBIP39(args.mpk, args.addrs, args.addr_limit, args.addressdb, mnemonic,
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrpass.py", line 2512, in __init__
    self.btcrseed_wallet = btcrseed_cls.create_from_params(
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrseed.py", line 1633, in create_from_params
    self = super(WalletEthereum, cls).create_from_params(*args, **kwargs)
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrseed.py", line 681, in create_from_params
    self = cls(path, loading=True)
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrseed.py", line 1623, in __init__
    super(WalletEthereum, self).__init__(path, loading)
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrseed.py", line 1045, in __init__
    super(WalletBIP39, self).__init__(path, loading)
  File "/home/keith/Desktop/btcrecover-master/btcrecover/btcrseed.py", line 649, in __init__
    if path_indexes[-1] == "":
IndexError: list index out of range

Any help on this would be much appreciated.

I have reinstalled BTCrecover requirements and all tests are complete, even reinstalled a fresh Ubuntu 20.04.2 LTS

**Comment by 3rdIteration** [comment]
Should be fixed in https://github.com/3rdIteration/btcrecover/commit/1b8eae1bfdd76764e9d79355c7e18697de3b337c

**Comment by InkParadox** [comment]
Thank you for the prompt fix, I can confirm now the program is working as it should. may god bless you

**Comment by 3rdIteration** [comment]
Good to hear :)
