### ISSUE TITLE
How can I brute force certain path(s)?

### ISSUE THREAD

**Issue by AngeloMetal** [3rdIteration/btcrecover#131]
Is it possible to brute force certain paths? I see an option ``--bip32-path`` but it doesn't work. Specifically this is what I get once I enter ``seedrecover.py --big-typos 1 --bip32-path "m/84'/0'/0'/1/0"`` :

**It opens windows explorer, I press cancel.**
**I choose BIP39**
Then:
```
Traceback (most recent call last):
  File "C:\Users\bymet\Pictures\btcrecover2\seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "C:\Users\bymet\Pictures\btcrecover2\btcrecover\btcrseed.py", line 2474, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
  File "C:\Users\bymet\Pictures\btcrecover2\btcrecover\btcrseed.py", line 682, in create_from_params
    self = cls(path, loading=True)
  File "C:\Users\bymet\Pictures\btcrecover2\btcrecover\btcrseed.py", line 1046, in __init__
    super(WalletBIP39, self).__init__(path, loading)
  File "C:\Users\bymet\Pictures\btcrecover2\btcrecover\btcrseed.py", line 642, in __init__
    for arg_path in arg_derivationpath.split(","):
AttributeError: 'list' object has no attribute 'split'

```

**Comment by 3rdIteration** [comment]
Firstly, the error you are seeing was fixed a few days ago, so just download the repo master again.

Secondly, if you are after the first change address on the first account (As this is what the derivation path you have specified would indicate), then the command you want is:
python seedrecover.py --big-typos 1 --bip32-path "m/84'/0'/0'/1"

By default, the following paths are checked for each wallet type: https://btcrecover.readthedocs.io/en/latest/bip39-accounts-and-altcoins/

You can also just edit those text files if you want.

**Comment by AngeloMetal** [comment]
Thank you, solved.
