### ISSUE TITLE
--enable-opencl Interrupted after finishing password # 0 Error

### ISSUE THREAD

**Issue by orangedecimation69** [3rdIteration/btcrecover#146]
**After successfully enabling GPU Acceleration yesterday, something appears to have broken. When I run the following command:**

python3 btcrecover-master/btcrecover.py --wallet wallets/wallet.aes.json --tokenlist tokens/okens.txt --enable-opencl

**Yesterday this command performed perfectly, today I am met with the following error:**

[Errno 2] No such file or directory: 'lib/opencl_brute/worker/generic/sha1.cl'--
[Errno 2] No such file or directory: 'lib/opencl_brute/worker/generic/sha1.cl'

Interrupted after finishing password # 0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/user/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 6052, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "/Users/user/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 1796, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if (not isinstance(self.opencl_algo,int)) \
  File "/Users/user/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 1849, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha1, passwords, salt_and_iv, iter_count, 32)
  File "/Users/user/Downloads/btcrecover-master/lib/opencl_brute/opencl.py", line 559, in cl_pbkdf2
    prg = ctx[0]
TypeError: 'int' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Downloads/btcrecover-master/btcrecover.py", line 39, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "/Users/user/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 6617, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "/Users/user/.pyenv/versions/3.9.1/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: 'int' object is not subscriptable

**I have checked and updated all the required packages, as well as updating openCL (I am running off the M1 processor) - all updates appear to be successful. Any ideas?**

**Comment by 3rdIteration** [comment]
It looks like the sha1.cl file is missing. Nothin in opencl_brute has changed for weeks (see here: https://github.com/3rdIteration/btcrecover/tree/master/lib/opencl_brute) so are you sure you didn't just delete it?

**Comment by orangedecimation69** [comment]
Stupid mistake! Thank you very much :)
