### ISSUE TITLE
--enable-opencl error

### ISSUE THREAD

**Issue by kipilk0** [3rdIteration/btcrecover#160]
C:\Users\btcrecover\AppData\Local\Programs\Python\Python38\lib\site-packages\pyopencl\__init__.py:267: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "

OpenCL: Available Platforms
Platform 0 - Name Intel(R) CPU Runtime for OpenCL(TM) Applications, Vendor Intel(R) Corporation

OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  409600

**Comment by 3rdIteration** [comment]
Don't use your CPU for Opencl...

**Comment by kipilk0** [comment]
```
C:\btcrecover>python seedrecover.py --opencl-info

Starting seedrecover 1.8.0-CryptoGuide, btcrecover 1.8.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints

============================================================
OpenCL Platforms and Devices
============================================================
Platform 0 - Name: Intel(R) CPU Runtime for OpenCL(TM) Applications
Platform 0 - Vendor: Intel(R) Corporation
Platform 0 - Version: OpenCL 2.1 WINDOWS
Platform 0 - Profile: FULL_PROFILE
 --------------------------------------------------------

 Device 0 - Name: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
 Device 0 - Type: ALL | CPU
 Device 0 - Max Clock Speed: 3300 Mhz
 Device 0 - Compute Units: 20
 Device 0 - Local Memory: 32 KB
 Device 0 - Constant Memory: 128 KB
 Device 0 - Global Memory: 64 GB
 Device 0 - Max Buffer/Image Size: 16303 MB
 Device 0 - Max Work Group Size: 8192

```

But i have RTX 3080 , is btcrecover support this GPU ?

**Comment by 3rdIteration** [comment]
You don't seem to have working drivers for it, otherwise it would be listed
as an opencl device.

**Comment by kipilk0** [comment]
```
C:\btcrecover>python seedrecover.py --no-dupchecks --language EN --addr-limit 1 --dsw --addressdb addresses-BTC.db --no-eta --mnemonic-length 12 --wallet-type BIP39 --enable-opencl --opencl-platform 0

Starting seedrecover 1.8.0-CryptoGuide, btcrecover 1.8.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
Loading address database ...
Loaded 810748265 addresses from database ...
Using the 'en' wordlist.
'x' was in your seed, but there is no similar seed word.
2021-04-15 01:39:36 : Phase 1/4: up to 2 mistakes, excluding entirely different seed words.
Not enough entirely different seed words permitted; skipping this phase.
2021-04-15 01:39:36 : Search Complete
 Seed not found
2021-04-15 01:39:36 : Phase 2/4: 1 mistake which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation
Platform 1 - Name Intel(R) CPU Runtime for OpenCL(TM) Applications, Vendor Intel(R) Corporation

OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

2021-04-15 01:39:37 : Using 20 worker threads
Context failed: OUT_OF_RESOURCES.00  P/s

Interrupted after finishing password # 0
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\btcrecover\btcrecover\btcrpass.py", line 6154, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcrecover\btcrecover\btcrseed.py", line 866, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(mnemonic_ids_list) if not isinstance(self.opencl_algo,int) \
  File "C:\btcrecover\btcrecover\btcrseed.py", line 913, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha512[i], cleaned_mnemonic_ids_list,
TypeError: 'int' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "C:\btcrecover\btcrecover\btcrseed.py", line 2700, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "C:\btcrecover\btcrecover\btcrseed.py", line 2121, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "C:\btcrecover\btcrecover\btcrpass.py", line 6719, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
TypeError: 'int' object is not subscriptable
```

RTX 3080

**Comment by 3rdIteration** [comment]
20 worker threads is too many for your GPU and you are exhausting your GPU
vmem, try with 10 threads.
