### ISSUE TITLE
download-blockchain-wallet.py error

### ISSUE THREAD

**Issue by kipilk0** [3rdIteration/btcrecover#174]
```
Please enter your wallet's ID (e.g. 9bb4c672-563e-4806-9012-a3e8f86a0eca)
> 9bb4c672-563e-4806-9012-a3e8f86a0eca
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [WinError 10049]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\btcrecover\extract-scripts\download-blockchain-wallet.py", line 81, in <module>
    auth_token = do_request_json("sessions", "")["token"]  # a POST request
  File "C:\btcrecover\extract-scripts\download-blockchain-wallet.py", line 76, in do_request_json
    return json.load(do_request(query, body))
  File "C:\btcrecover\extract-scripts\download-blockchain-wallet.py", line 70, in do_request
    return urllib.request.urlopen(req, context=ctx)  # fixed because otherwise SSL errors abound
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10049] >

Press Enter to exit ...
```

**Comment by 3rdIteration** [comment]
I tried just now, with that same wallet ID and it worked fine. Are you using the latest code from the master of this repository?
