### ISSUE TITLE
seedrecover.py error 

### ISSUE THREAD

**Issue by Cometspoon** [3rdIteration/btcrecover#181]
When I try to run python seedrecover.py I get the following errors. Help is appreciated. 

Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
2021-05-10 17:19:38 : Phase 1/4: up to 2 mistakes, excluding entirely different seed words.
2021-05-10 17:19:39 : Using 64 worker threads
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()----------------------------------------] 0:00:00, ETA:  --:--:--
  File "c:\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Python39\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\Python39\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\Python39\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
4269 of 4269 [######################################################] 0:00:00,

**Comment by 3rdIteration** [comment]
Have you tried with less threads, something like 32 to start with.

**Comment by Cometspoon** [comment]
Ok that was it, thanks.

**Comment by 3rdIteration** [comment]
Which operating system are you in and what sort of CPU do you have?

**Comment by Cometspoon** [comment]
Windows 10 home, Threadripper 3970X.

**Comment by 3rdIteration** [comment]
Did it throw a warning that Windows doesn't support more than 60; threads?

**Comment by Cometspoon** [comment]
Nope.

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/e9f42a4a5fea8dfaf18fd4c4faf98542b20fed7c so it should handle that batter now for systems with more than 60 logical processors.
