### ISSUE TITLE
Issue with OpenCL

### ISSUE THREAD

**Issue by byGits** [3rdIteration/btcrecover#185]
I'm trying to run this on an Ubuntu 20.04 with a 2080 Ti, Nvidia drivers and CUDA 11.2 are installed (Python version is 3.8.5).

Installed BTCRecover with:

> sudo apt update

> sudo apt install -y python3-pyopencl python3-pip autoconf automake pkg-config libgtk-3-dev build-essential unzip gcc python3.8-dev

> wget https://github.com/3rdIteration/btcrecover/archive/master.zip && unzip master.zip && cd btcrecover-master

> sudo -H pip3 install -r requirements.txt

No errors on installation, but when I try to use opencl, or even run `python3 btcrecover.py --opencl-info`, I get this error:

> Starting btcrecover 1.10.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints
> Traceback (most recent call last):
>  File "btcrecover.py", line 38, in <module>
>   btcrpass.parse_arguments(sys.argv[1:])
>  File "/home/usergpu/btcrecover-master/btcrecover/btcrpass.py", line 4143, in parse_arguments
>    info = opencl_information()
> NameError: name 'opencl_information' is not defined

I have also tried installing the following, but still the same:

> sudo apt install -y nvidia-cuda-toolkit nvidia-opencl-dev opencl-headers clinfo ocl-icd-libopencl1 ocl-icd-opencl-dev

Running `python3 -m btcrecover.test.test_passwords -v OpenCL_Tests` gives the output:

>  ... skipped 'requires OpenCL and a compatible device'
> ERROR: test_Electrum28_OpenCL_Brute (unittest.loader._FailedTest)
> AttributeError: type object 'Test07WalletDecryption' has no attribute 'test_Electrum28_OpenCL_Brute'

Any help is appreciated.

**Comment by byGits** [comment]
In case any one else has this issue, running 

`sudo pip3 install pyopencl --upgrade`

Seems to have solved the issue.

The installed version was 2019.1.1 (not sure why), now the pyopencl-2021.2.1 is installed and it seems to work fine.
