### ISSUE TITLE
NotImplementedError: Unsupported Blockchain wallet version 4

### ISSUE THREAD

**Issue by rfakit** [3rdIteration/btcrecover#204]
what can i do with this one

Starting btcrecover 1.11.0-Cryptoguide on Python 3.6.9 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "./btcrecover.py", line 38, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/root/test2/btcrecover/btcrecover/btcrpass.py", line 4649, in parse_arguments
    load_global_wallet(args.wallet)
  File "/root/test2/btcrecover/btcrecover/btcrpass.py", line 244, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "/root/test2/btcrecover/btcrecover/btcrpass.py", line 234, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "/root/test2/btcrecover/btcrecover/btcrpass.py", line 1759, in load_from_filename
    data, iter_count = cls._parse_encrypted_blockchain_wallet(wallet_file.read(MAX_WALLET_FILE_SIZE))  # up to 64M, typical size is a few k
  File "/root/test2/btcrecover/btcrecover/btcrpass.py", line 1790, in _parse_encrypted_blockchain_wallet
    raise NotImplementedError("Unsupported Blockchain wallet version " + str(data["version"]))
NotImplementedError: Unsupported Blockchain wallet version 4

**Comment by 3rdIteration** [comment]
When did you generate this wallet? (Is it really new?)

**Comment by 3rdIteration** [comment]
V4 supported added in https://github.com/3rdIteration/btcrecover/commit/4016a9c0a7433c3ac94d97da6747b4257d6f14f4

**Comment by 3rdIteration** [comment]
Just download from the master (not releases) and it will work fine for version 5 wallets. (If you are using gurnecs unmaintained version it won't work)

How old is this wallet?

**Comment by RickDeckcard** [comment]
I habe try with gunec version and with your version. Whats the master not release?
In the test some lptio s skip because i cant install some dependencies like protobuf.

**Comment by 3rdIteration** [comment]
Did you follow the installation guide here
https://btcrecover.readthedocs.io/en/latest/INSTALL/
