### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 44-47: character maps to <undefined>

### ISSUE THREAD

**Issue by AndrewEggg** [3rdIteration/btcrecover#253]
Interrupted after finishing password # 83299356
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\J\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\J\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 6690, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\J\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 1912, in return_verified_password_or_false
    else self._return_verified_password_or_false_cpu(passwords)
  File "C:\Users\J\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 1949, in _return_verified_password_or_false_cpu
    if self.check_blockchain_decrypted_block(unencrypted_block, password):
  File "C:\Users\J\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 1876, in check_blockchain_decrypted_block
    logfile.write(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") +
  File "C:\Users\J\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 44-47: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "btcrecover.py", line 39, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\J\Downloads\btcrecover-master\btcrecover-master\btcrecover\btcrpass.py", line 7256, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "C:\Users\J\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
UnicodeEncodeError: 'charmap' codec can't encode characters in position 44-47: character maps to <undefined>

**Comment by 3rdIteration** [comment]
Do you know exactly whuch password this failed on? (Looks like some of the characters in it are what is causing the issue)

What type of wallet was this for?
