### ISSUE TITLE
Helium Recovery failure NACL has no attribute bindings

### ISSUE THREAD

**Issue by KnightAR** [3rdIteration/btcrecover#289]
python seedrecover.py --wallet-type helium --addrs 13hP2Vb1XVcMYrVNdwUW4pF3ZDj8CnET92zzUHqYp7DxxzVASbB --mnemonic "arm hundred female steel describe tip physical weapon peace write advice" --enable-opencl

```
Starting seedrecover 1.11.0-CryptoGuide, btcrecover 1.11.0-Cryptoguide on Python 3.9.9 64-bit, 21-bit unicodes, 64-bit ints
btcrseed
* * * * * * * * * * * * * * * * * * * *
*          Security: Warning          *
* * * * * * * * * * * * * * * * * * * *

Most crypto wallet software and hardware wallets go to great lengths to protect your wallet password, seed phrase and private keys. BTCRecover isn't designed to offer this level of security, so it is possible that malware on your PC could gain access to this sensitive information while it is stored in memory in the use of this tool...

As a precaution, you should run this tool in a secure, offline environment and not simply use your normal, internet connected desktop environment... At the very least, you should disconnect your PC from the network and only reconnect it after moving your funds to a new seed... (Or if you run the tool on your internet conencted PC, move it to a new seed as soon as practical)

You can disable this message by running this tool with the --dsw argument

* * * * * * * * * * * * * * * * * * * *
*          Security: Warning          *
* * * * * * * * * * * * * * * * * * * *

Using the 'en' wordlist.
Assuming a 12 word mnemonic. (This can be overridden with --mnemonic-length)
Seed sentence was too short, inserting 1 word into each guess.
OpenCL: Auto Selecting Best Platform
2021-11-21 22:20:40 : Phase 1/4: up to 2 mistakes, excluding entirely different seed words.
Not enough entirely different seed words permitted; skipping this phase.
2021-11-21 22:20:40 : Search Complete
 Seed not found
2021-11-21 22:20:40 : Phase 2/4: 1 mistake which can be an entirely different seed word.

OpenCL: Available Platforms
Platform 0 - Name NVIDIA CUDA, Vendor NVIDIA Corporation

OpenCL: Auto Selecting Best Platform
OpenCL: Using Platform: 0
OpenCL: Using Work Group Size:  51200

Wallet Type: btcrseed.WalletHelium
Traceback (most recent call last):
  File "c:\wsl\btcrecover\seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "c:\wsl\btcrecover\btcrecover\btcrseed.py", line 3319, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "c:\wsl\btcrecover\btcrecover\btcrseed.py", line 2735, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "c:\wsl\btcrecover\btcrecover\btcrpass.py", line 7737, in main
    loaded_wallet.return_verified_password_or_false(list(
  File "c:\wsl\btcrecover\btcrecover\btcrseed.py", line 2335, in return_verified_password_or_false
    else self._return_verified_password_or_false_cpu(mnemonic_ids_list)
  File "c:\wsl\btcrecover\btcrecover\btcrseed.py", line 2342, in _return_verified_password_or_false_cpu
    if self._verify_seed(mnemonic_ids):
  File "c:\wsl\btcrecover\btcrecover\btcrseed.py", line 2324, in _verify_seed
    public_key, secret_key = nacl.bindings.crypto_sign_seed_keypair(seed)
AttributeError: module 'nacl' has no attribute 'bindings'
```

With and without OpenCL it gives the same error. I have nacl installed.

**Comment by KnightAR** [comment]
Oh I forgot, I'm using windows 10. I have not tried native Linux yet.

**Comment by KnightAR** [comment]
```
Package      Version
------------ -------------
appdirs      1.4.4
asn1crypto   1.4.0
bitstring    3.1.9
cffi         1.15.0
coincurve    15.0.1
colorama     0.4.4
coverage     6.1.2
green        3.2.6
lxml         4.6.4
numpy        1.21.4
pip          21.2.4
protobuf     3.14.0
pycparser    2.21
pycryptodome 3.9.9
PyNaCl       1.4.0
pyopencl     2021.2.9+cl12
pytools      2021.2.9
setuptools   58.1.0
six          1.16.0
Unidecode    1.3.2
```

**Comment by 3rdIteration** [comment]
Have reproduced this in a fresh Win10 VM, so that's good. Basically installing requirements-full.txt fixes this, so I just need to go back and double check which dependency from there is missing.

**Comment by 3rdIteration** [comment]
Can you just try installing py_crypto_hd_wallet

**Comment by 3rdIteration** [comment]
fixed in https://github.com/3rdIteration/btcrecover/commit/0f4a8888c65279598d55806acb9b0553673e603b

Thanks for the report
