### ISSUE TITLE
seedrecover.py - AttributeError: 'Namespace' object has no attribute 'keep_tokens_order'

### ISSUE THREAD

**Issue by okanisis** [3rdIteration/btcrecover#301]
```
seedrecover 1.5.0-CryptoGuide, btcrecover 1.6.0-Cryptoguide on Python 3.10.1 64-bit, 21-bit unicodes, 64-bit ints
```

Error:
```
Interrupted after generating 0 passwords
Traceback (most recent call last):
  File "/home/saultdon/Pictures/nft/btcrecover/btcrecover-1.6.0/seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "/home/saultdon/Pictures/nft/btcrecover/btcrecover-1.6.0/btcrecover/btcrseed.py", line 2656, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "/home/saultdon/Pictures/nft/btcrecover/btcrecover-1.6.0/btcrecover/btcrseed.py", line 2083, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "/home/saultdon/Pictures/nft/btcrecover/btcrecover-1.6.0/btcrecover/btcrpass.py", line 5951, in main
    for password in password_iterator:
  File "/home/saultdon/Pictures/nft/btcrecover/btcrecover-1.6.0/btcrecover/btcrpass.py", line 4626, in password_generator
    for password_base in base_password_generator() if callable(base_password_generator) else base_password_generator:
  File "/home/saultdon/Pictures/nft/btcrecover/btcrecover-1.6.0/btcrecover/btcrpass.py", line 4756, in tokenlist_base_password_generator
    if args.keep_tokens_order:
AttributeError: 'Namespace' object has no attribute 'keep_tokens_order'
```

**Comment by 3rdIteration** [comment]
Just run the latest code from master, not the 1.5.0 release.
