### ISSUE TITLE
error after running for a few minutes

### ISSUE THREAD

**Issue by optickavarka** [3rdIteration/btcrecover#328]
Notice: Loading File:  crackstation-human-only.txt
3508224 of 63921384 [#---------------------------------] 0:06:15, ETA:  1:47:39
Interrupted after finishing password # 3509248
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\lov\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\btcrecover\btcrpass.py", line 7890, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\btcrecover\btcrpass.py", line 2162, in return_verified_password_or_false
    return self._return_verified_password_or_false_opencl(passwords) if (not isinstance(self.opencl_algo,int)) \
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\btcrecover\btcrpass.py", line 2221, in _return_verified_password_or_false_opencl
    clResult = self.opencl_algo.cl_pbkdf2(self.opencl_context_pbkdf2_sha1, passwords, salt_and_iv, iter_count, 32)
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\lib\opencl_brute\opencl.py", line 705, in cl_pbkdf2
    result = concat(self.opencl_ctx.run(bufStructs, func, iter(passwordlist), salt))
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\lib\opencl_brute\opencl.py", line 524, in concat
    return [obj for lval in ll for obj in lval]
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\lib\opencl_brute\opencl.py", line 524, in <listcomp>
    return [obj for lval in ll for obj in lval]
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\lib\opencl_brute\opencl.py", line 225, in run
    assert paddedLenFunc(pwLen, hashBlockSize_bits // 8) <= inBufSize_bytes, \
AssertionError: password #458, '3ORIWILLP\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\3ORIWILLPEE' (length 148) exceeds the input buffer (length 128) when padded
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\btcrecover.py", line 39, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\lov\Desktop\btcrecover\btcrecover-master\btcrecover\btcrpass.py", line 8456, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "C:\Users\lov\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
AssertionError: password #458, '3ORIWILLP\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\3ORIWILLPEE' (length 148) exceeds the input buffer (length 128) when padded

running this against wallet.aes.json file with rtx 2060 laptop gpu
using this command 

python btcrecover.py --enable-opencl --wallet wallet.aes.json --passwordlist crackstation-human-only.txt

**Comment by 3rdIteration** [comment]
Same issue as here: https://github.com/3rdIteration/btcrecover/issues/276
