### ISSUE TITLE
Add Pure Python version of ripemd160 (Needed on some platforms, particularly given recent OpenSSL changes)

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#355]
Similar issue, as well as a simple implementation to use here: https://github.com/diybitcoinhardware/embit/commit/2e293b000d20562327151c72a4aed672d0a944bc

Solution to restore support here:
https://github.com/openssl/openssl/issues/16994 

Fixing this issue will involve

- [ ] 1. Adding pure python implementation (with warnings)
- [ ] 2. Adding documentation to restore openssl supported functionality

**Comment by Pymmdrza** [comment]
```shell:
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmdrza/Desktop/soft/btc500.py", line 294, in <module>
    data_wallet()
  File "/home/mmdrza/Desktop/soft/btc500.py", line 36, in data_wallet
    bip32_child_key_obj = bip32_root_key_obj.ChildKey(
  File "/home/mmdrza/.local/lib/python3.10/site-packages/bip32utils/BIP32Key.py", line 241, in ChildKey
    return self.CKDpriv(i)
  File "/home/mmdrza/.local/lib/python3.10/site-packages/bip32utils/BIP32Key.py", line 193, in CKDpriv
    return BIP32Key(secret=secret, chain=Ir, depth=self.depth+1, index=i, fpr=self.Fingerprint(), public=False, testnet=self.testnet)
  File "/home/mmdrza/.local/lib/python3.10/site-packages/bip32utils/BIP32Key.py", line 283, in Fingerprint
    return self.Identifier()[:4]
  File "/home/mmdrza/.local/lib/python3.10/site-packages/bip32utils/BIP32Key.py", line 278, in Identifier
    return hashlib.new('ripemd160', sha256(cK).digest()).digest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160

```

**Comment by 3rdIteration** [comment]
Yep, that's exactly the error, what platform are you on?

You can just use the Android-Termux branch and it has the pure-python implementation, alternatively you can apply the fix that is linked via the OpenSSL wiki.

**Comment by 3rdIteration** [comment]
Fixed in https://github.com/3rdIteration/btcrecover/commit/63b20c9045405efa6c6105ac7d338ac365e12f3a
