### ISSUE TITLE
argument --savevalidseeds I get this error

### ISSUE THREAD

**Issue by dvvvsh** [3rdIteration/btcrecover#359]
2022-05-30 03:51:34 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.
Wallet Type: btcrseed.WalletBIP39
2022-05-30 03:51:35 : Using 8 worker threads
Process Process-9: 0:00:04  rate:  41.64 kP/s                                                                                                                                                             
Traceback (most recent call last):
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jonathandoe/btcrecover/btcrecover/btcrpass.py", line 8331, in write_checked_seeds
    while worker_out_queue.qsize() < 10: #If the workers haven't started filling the queue yet, just sleep
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
/ 415854  elapsed: 0:00:06  rate:  67.98 kP/s

**Comment by 3rdIteration** [comment]
Can you produce a test seed so that you can post something that is reproducible.
