### ISSUE TITLE
UnboundLocalError: local variable 'ciphertext' referenced before assignment

### ISSUE THREAD

**Issue by hagbase** [3rdIteration/btcrecover#374]
Trying to run gpu perfomance test/tuning for btccore wallet.
Fresh Win 10 Pro 21H2 

GPU Tests pass except for multi GPU.
Error occurs on both test wallet provided by btcrecover and my wallet and data extract.

Test/performance vs wallet.dat:

2022-07-03 12:39:00 : Using OpenCL ALL | GPU NVIDIA GeForce RTX 3060 Ti
\ 12288  elapsed: 0:00:01  rate:   7.33 kP/s
Interrupted after finishing password # 12288
Traceback (most recent call last):
  File "C:\btcrecover-1.6.0\btcrecover.py", line 39, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 6200, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 5635, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 422, in return_verified_password_or_false
    return self._return_verified_password_or_false_gpu(passwords)
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 589, in _return_verified_password_or_false_gpu
    part_master_key = aes256_cbc_decrypt(derived_key[:32], self._part_encrypted_master_key[:16], self._part_encrypted_master_key[16:])
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 2649, in <lambda>
    new_aes(key, Crypto.Cipher.AES.MODE_CBC, iv).decrypt(ciphertext)
  File "C:\Users\gpu\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 229, in decrypt
    plaintext = create_string_buffer(len(ciphertext))
UnboundLocalError: local variable 'ciphertext' referenced before assignment

Test/performance vs data extract:

2022-07-03 12:52:41 : Using OpenCL ALL | GPU NVIDIA GeForce RTX 3060 Ti
/ 38912  elapsed: 0:00:02  rate:  13.75 kP/s
Interrupted after finishing password # 38912
Traceback (most recent call last):
  File "C:\btcrecover-1.6.0\btcrecover.py", line 39, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 6200, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 5635, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 422, in return_verified_password_or_false
    return self._return_verified_password_or_false_gpu(passwords)
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 589, in _return_verified_password_or_false_gpu
    part_master_key = aes256_cbc_decrypt(derived_key[:32], self._part_encrypted_master_key[:16], self._part_encrypted_master_key[16:])
  File "C:\btcrecover-1.6.0\btcrecover\btcrpass.py", line 2649, in <lambda>
    new_aes(key, Crypto.Cipher.AES.MODE_CBC, iv).decrypt(ciphertext)
  File "C:\Users\gpu\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Users\gpu\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Users\gpu\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 293, in _create_cbc_cipher
    return CbcMode(cipher_state, iv)
  File "C:\Users\gpu\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 106, in __init__
    self._state = SmartPointer(self._state.get(),
  File "C:\Users\gpu\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\Util\_raw_api.py", line 271, in __init__
    self._destructor = destructor
UnboundLocalError: local variable 'destructor' referenced before assignment

**Comment by 3rdIteration** [comment]
Can you provides the command that you used to reproduce this? (Ideally just using one of the wallets in the repo)

**Comment by hagbase** [comment]
Thanks for reply but this was faulty Hardware not an issue with btcrecover. 
My MSI B550m pro wasn't able to run a 3700x, everything runs fine now on a MSI B450 gaming plus.
