### ISSUE TITLE
UnboundLocalError: local variable 'wallet_data' referenced before assignment

### ISSUE THREAD

**Issue by mexfarmer** [3rdIteration/btcrecover#390]
Hello, I've been trying to use btcrecovery on linux and windows but I keep getting the same error, here's a shot of what I got on windows:

C:\btcrecover-master>python btcrecover.py --wallet C:\btcrecover-master\Wallets\Ben --passwordlist ben.txt --typos-case --typos-repeat --typos-swap --typos-caps --enable-opencl --enable-gpu

Starting btcrecover 1.11.0-Cryptoguide on Python 3.10.9 64-bit, 21-bit unicodes, 64-bit ints
Warning: --typos COUNT not specified; assuming 1
Traceback (most recent call last):
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 291, in load_wallet
    with open(wallet_filename, "rb") as wallet_file:
PermissionError: [Errno 13] Permission denied: 'C:\\btcrecover-master\\Wallets\\Ben'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\btcrecover-master\btcrecover.py", line 38, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 6005, in parse_arguments
    load_global_wallet(args.wallet)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 319, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 300, in load_wallet
    return WalletMetamask.load_from_filename(wallet_filename)
  File "C:\btcrecover-master\btcrecover\btcrpass.py", line 3033, in load_from_filename
    wallet_json = json.loads(wallet_data)
UnboundLocalError: local variable 'wallet_data' referenced before assignment

I really could use some help

**Comment by 3rdIteration** [comment]
PermissionError: [Errno 13] Permission denied: 'C:\btcrecover-master\Wallets\Ben'
