### ISSUE TITLE
this is happen when i use seedrecover.py in wide range seed A>Z

### ISSUE THREAD

**Issue by ayiphelmy** [3rdIteration/btcrecover#434]
Interrupted after finishing password # 669220110
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrpass.py", line 8365, in return_verified_password_or_false
    return loaded_wallet.return_verified_password_or_false(passwords)
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrseed.py", line 958, in return_verified_password_or_false
    else self._return_verified_password_or_false_cpu(mnemonic_ids_list)
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrseed.py", line 967, in _return_verified_password_or_false_cpu
    if not self._verify_checksum(mnemonic_ids):
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrseed.py", line 1417, in _verify_checksum
    return ord(hashlib.sha256(entropy_bytes).digest()[:1]) >> 8-cksum_len_in_bits \
ValueError: negative shift count
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\PROGRAMBTC\btcrecover-master\seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrseed.py", line 3710, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrseed.py", line 3098, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "G:\PROGRAMBTC\btcrecover-master\btcrecover\btcrpass.py", line 8931, in main
    for password_found, passwords_tried_last in password_found_iterator:
  File "C:\Python310\lib\multiprocessing\pool.py", line 870, in next
    raise value
ValueError: negative shift count

**Comment by 3rdIteration** [comment]
Can you create a test wallet and then include an actual command that reproduces this? (I have no idea what you are even trying to describe that causes this)
