### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by muradkhalimov** [3rdIteration/btcrecover#449]
Hi everyone

Just tried running this, getting this error please help(I have Python 3.12 though...):

Starting btcrecover 1.13.0-Cryptoguide on Python 3.8.9 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "btcrecover.py", line 38, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/Users/Murad/Desktop/btcrecover-master/btcrecover/btcrpass.py", line 5806, in parse_arguments
    tokenlist_file = open_or_use(args.tokenlist, "r", kwds.get("tokenlist"),
  File "/Users/Murad/Desktop/btcrecover-master/btcrecover/btcrpass.py", line 5460, in open_or_use
    if file.read(5) == br"{\rtf":
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by 3rdIteration** [comment]
Can you provide a tokenlist which demonstrates this issue?

**Comment by 3rdIteration** [comment]
Closed due to inactivity
