### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by watkins14** [3rdIteration/btcrecover#450]
Hi everyone, 

Please help with this issue, I have tried running this on python 3.11 and i am now using 3.12. I get the same error when using --passwordlist and  --tokenlist. 

I have attached the basic password list used below. 

C:\Users\ejwat\Downloads\btcrecover-master>python btcrecover.py --wallet ./metamask-wallet-file  --passwordlist test-password.txt

Starting btcrecover 1.13.0-Cryptoguide on Python 3.12.2 64-bit, 21-bit unicodes, 64-bit ints
Traceback (most recent call last):
  File "C:\Users\ejwat\Downloads\btcrecover-master\btcrecover.py", line 38, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\Users\ejwat\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 6208, in parse_arguments
    load_global_wallet(args.wallet)
  File "C:\Users\ejwat\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 339, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ejwat\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 320, in load_wallet
    return WalletMetamask.load_from_filename(wallet_filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ejwat\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 3105, in load_from_filename
    wallet_json = json.loads(wallet_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ejwat\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ejwat\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ejwat\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[test-password.txt](https://github.com/3rdIteration/btcrecover/files/14480658/test-password.txt)

Cheers!

**Comment by 3rdIteration** [comment]
The problem is the wallet file you are providing isn't a valid metamask wallet
