### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './derivationpath-lists/ETH.txt'

### ISSUE THREAD

**Issue by kuzmichev1max** [3rdIteration/btcrecover#489]
Traceback (most recent call last):
  File "/Users/max/Desktop/btcrecover/seedrecover.command", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Desktop/btcrecover/btcrecover/btcrseed.py", line 3888, in main
    loaded_wallet = wallet_type.create_from_params(**create_from_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Desktop/btcrecover/btcrecover/btcrseed.py", line 2089, in create_from_params
    self = super(WalletEthereum, cls).create_from_params(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Desktop/btcrecover/btcrecover/btcrseed.py", line 1074, in create_from_params
    self = cls(path, loading=True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Desktop/btcrecover/btcrecover/btcrseed.py", line 2078, in __init__
    if not path: path = load_pathlist("./derivationpath-lists/ETH.txt")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/max/Desktop/btcrecover/btcrecover/btcrseed.py", line 234, in load_pathlist
    pathlist_file = open(pathlistFile, "r")
                    ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './derivationpath-lists/ETH.txt'

**Comment by 3rdIteration** [comment]
You either botched the install or tried to run the command from somewhere other than the BTCRecover directory.

This isn't a bug, so further questions can happen in the YouTube comments section.
