### ISSUE TITLE
AssertionError (assert outer_iterations > 0)

### ISSUE THREAD

**Issue by Karl483r** [3rdIteration/btcrecover#524]
Hi,

thanks for your work! I think I know my mnemonic and have a list of possible passwords. So I tried:
`python3 seedrecover.py  --wallet-type bip39 --addressdb ../addresses-BTC-2011-to-2021-03-31.db --passphrase-list ../passwords --mnemonic "...." --addr-limit 100`

I get the following output:
```
Starting seedrecover 1.13.0-CryptoGuide, btcrecover 1.13.0-Cryptoguide on Python 3.12.3 64-bit, 21-bit unicodes, 64-bit ints
btcrseed
...
Loading address database ...
Loaded 804797813 addresses from database ...
Using the 'en' wordlist.
Assuming a 24 word mnemonic. (This can be overridden with --mnemonic-length)
Initial seed guess has a valid checksum (0.39% chance).
2024-11-27 18:51:20 : Phase 1/5: 1 mistake, excluding entirely different seed words.
Wallet Type: btcrseed.WalletBIP39
Traceback (most recent call last):
  File "/home/ubuntu/btcrecover/seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/btcrecover/btcrecover/btcrseed.py", line 4085, in main
    mnemonic_found = run_btcrecover(**phase_params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/btcrecover/btcrecover/btcrseed.py", line 3464, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
                                      ^^^^^^^^^^^^^^^
  File "/home/ubuntu/btcrecover/btcrecover/btcrpass.py", line 8801, in main
    assert outer_iterations > 0
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Any idea how I can fix this? Without the password list it seems to run. I tried it on a Mac and on Ubuntu.

Thank you,
Karl

**Comment by Sarahclain** [comment]
Hello @Karl483r 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WAL07638
Please see the link below to our dedicated support line:
[Wallet DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Sarahclain** [comment]
@Karl483r is your VPN on ?

**Comment by Sarahclain** [comment]
@Karl483r  if your VPN is on turn it off and refresh your browser and try it again you should be able to get it

**Comment by 3rdIteration** [comment]
Can you generate a test wallet and provide a command that can be pasted to reproduce this error?

**Comment by Karl483r** [comment]
I think the issue is related to the length of the password file.
```
seq 1 200000 > testPWs
python3 seedrecover.py  --wallet-type bip39 --addressdb ../addresses-BTC-2011-to-2021-03-31.db --passphrase-list testPWs --mnemonic "biology away veteran slice curtain imitate cargo luggage tunnel update volume ill flee secret spare crawl update plug animal rally avocado better traffic lock" --addr-limit 100
```
These commands replicate the error on my system. I think you do not even need the addressdb

**Comment by 3rdIteration** [comment]
fixed in https://github.com/3rdIteration/btcrecover/commit/40f53d0ceb4f93e13fb3cddee9aab73569f45087
